# Generated by Django 5.2.8 on 2025-11-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(default='presencial'),
            preserve_default=False,
        ),
    ]
