# Generated by Django 5.2.8 on 2025-11-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_vaga_tipo_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='area',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia da Informação'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('financas', 'Finanças e Contabilidade'), ('marketing', 'Marketing e Vendas'), ('rh', 'Recursos Humanos'), ('juridico', 'Jurídico'), ('engenharia', 'Engenharia'), ('design', 'Design e Criatividade'), ('administrativo', 'Administrativo'), ('atendimento', 'Atendimento ao Cliente'), ('logistica', 'Logística e Transporte'), ('producao', 'Produção e Indústria'), ('vendas', 'Vendas e Comercial'), ('comunicacao', 'Comunicação e Mídia'), ('meio_ambiente', 'Meio Ambiente'), ('pesquisa', 'Pesquisa e Desenvolvimento'), ('turismo', 'Turismo e Hotelaria'), ('outros', 'Outros')], default='tecnologia', max_length=50, verbose_name='Área de Atuação'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20),
        ),
    ]
