# Generated by Django 5.2.8 on 2025-11-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vaga_area_alter_vaga_tipo_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='tipo_contratacao',
            field=models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagio', 'Estágio'), ('jovem_aprendiz', 'Jovem Aprendiz'), ('freelancer', 'Freelancer'), ('tempo_determinado', 'Tempo Determinado'), ('autonomo', 'Autônomo'), ('trainee', 'Trainee'), ('voluntario', 'Voluntário'), ('outros', 'Outros')], default='clt', max_length=20, verbose_name='Tipo de Contratação'),
        ),
    ]
