# Generated by Django 5.2.8 on 2025-11-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_vaga_tipo_contratacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('entrevista', 'Chamado para entrevista'), ('rejeitado', 'Rejeitado'), ('contratado', 'Contratado')], default='pendente', max_length=20),
        ),
    ]
