# Generated by Django 5.2.6 on 2025-12-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_candidatura_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensagem',
        ),
    ]
