# Generated by Django 5.2.6 on 2025-10-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioadaptado',
            name='is_empresa',
            field=models.BooleanField(default=False),
        ),
    ]
