# Generated by Django 5.2.6 on 2025-10-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarioadaptado_is_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioadaptado',
            old_name='linkportfolio',
            new_name='link_portfolio',
        ),
        migrations.AddField(
            model_name='usuarioadaptado',
            name='tipo_usuario',
            field=models.CharField(choices=[('candidato', 'Candidato'), ('empresa', 'Empresa')], default='candidato', max_length=20),
        ),
    ]
