# Generated by Django 5.2.6 on 2025-10-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_linkportfolio_usuarioadaptado_link_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioadaptado',
            name='is_candidato',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarioadaptado',
            name='link_portfolio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
