# Generated by Django 5.2.6 on 2025-10-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarioadaptado_is_candidato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioadaptado',
            name='is_candidato',
            field=models.BooleanField(default=True),
        ),
    ]
