# Generated by Django 5.2.6 on 2025-11-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuarioadaptado_is_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioadaptado',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
