# Generated by Django 5.2.6 on 2025-11-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
    ]
